[tool.poetry]
name = "personal-site-backend"
version = "1.0.0"
description = "Backend microservice for my personal website"
authors = ["Matthew Gleich <matthewgleich@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.6 <4.0"
firebase_admin = "^4.2.0"
stravalib = "^0.10.2"
PyGithub = "^1.51"
